config/routes.rb
PromorpheusBeta::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  resources :composers
  resources :albums
  resources :songs
  resources :genres
  resources :setlists
  resources :tags

  root to: 'sessions#new'

  match '/home', to: "pages#home"

  match '/signup', to: 'users#new'
  
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/music', to: "songs#index"

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :album_name, :composer_name, :composer_id

  belongs_to :composer
  has_many :songs

end

app/models/composer.rb
class Composer < ActiveRecord::Base
  attr_accessible :name

  has_many :albums
  has_many :songs, :through => :albums

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  attr_accessible :name

  has_many :songs

end

app/models/setlist.rb
class Setlist < ActiveRecord::Base
  attr_accessible :title, :description, :performance_date

  belongs_to :user
  has_and_belongs_to_many :songs, join_table: "setlists_songs"

  validates :title, presence: true

  default_scope order: 'setlists.created_at ASC'

  def self.search(search)
  	if search
  		where( "title LIKE ? OR description LIKE ? OR performance_date LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%" )
  	else
  		scoped
  	end
  end

end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :title, :composer_name, :album_name, :album_id, :genre_name, :genre_id

  belongs_to :album
  belongs_to :genre

  has_and_belongs_to_many :tags, join_table: "songs_tags"
  has_and_belongs_to_many :setlists, join_table: "setlists_songs"

  def self.search(search)
  	if search
  		where( "title LIKE ? OR composer_name LIKE ? OR album_name LIKE ? OR genre_name LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%" )
  	else
  		scoped
  		# puts "Sorry. Nothing found."
  	end
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :tag
  has_and_belongs_to_many :songs, join_table: "songs_tags"

  validates :tag, presence: true, length: { maximum: 12 }

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  has_many :setlists
  has_many :songs, :through => :setlists

  before_save { |user| user.email = user.email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX},
  						uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def admin?
  	admin
  end

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  	include SessionsHelper

  	# force signout to prevent CSRF attacks
	def handle_unverified_request
		sign_out
		super
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by_email(params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			# Sign the user in, redirect to main page
			sign_in user
			redirect_to "/home"
		else
			# create and error message and re-render signin form
			flash.now[:error] = "That email/password combination does not exist"
			render "new"
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/setlists_controller.rb
class SetlistsController < ApplicationController

	def index
		@setlists = current_user.setlists
	end

	def new
		@setlist = Setlist.new
	end

	def create
		@setlist = Setlist.new(params[:setlist])
		current_user.setlists << @setlist
		if @setlist.save
			flash[:success] = "Setlist successfully created"
			redirect_to setlists_path
		else
	        render 'new'
	    end
	end

	def destroy
		Setlist.find(params[:id]).destroy
		flash[:alert] = "Setlist successfully deleted"
		redirect_to :back
	end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    # @songs = Song.paginate( page: params[:page], per_page: 12)
    @songs = Song.search(params[:search]).paginate(per_page: 10, page: params[:page])
  end

    # respond_to do |format|
    #   format.html
    #   format.xml { render :xml => @pieces}
    # end
  # end
  
  # def new
  #   @piece = Piece.new
  #   respond_to do |format|
  #     format.html
  #   end
  # end
  
  # def create
  #   @piece = Piece.new(params[:piece])
  #   respond_to do |format|
  #     if @piece.save
  #       format.html { redirect_to(admin_music_index_path) }
  #     else
  #       format.html { render :action => :new }
  #     end
  #   end
  # end
  
  # def show
  #   @songs = Song.all
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update]

	def show
		@user = User.find(params[:id])
	end
	
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
      sign_in @user
      flash[:success] = "Welcome to AmateurMorpheus"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def signed_in_user
      redirect_to signin_url, notice: "Please sign in" unless signed_in?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "Promorph BETA 01"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end
end

app/helpers/setlists_helper.rb
module SetlistsHelper
end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar (http://gravatar.com/) for the given user.
	def gravatar_for(user, options = { size:50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end

end

app/views/layouts/_footer.html.erb
<div class="clear">
  <div id="footer">
    <div class="container">
      
      <div id="footer_links">
        <span><%= link_to "Help", "#" %></span>
        <span><%= link_to "Email Newsletter", "#" %></span>
        <span><%= link_to "Feedback", "#" %></span>
        <span><%= link_to "Share", "#" %></span>
        <span>Be Social:&nbsp;<%= link_to image_tag("footer_facebook_icon.png"), "#" %>&nbsp;<%= link_to image_tag("footer_twitter_icon.png"), "#" %></span>
      </div>
    
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div id="header">
    <div class="container">

    <div id="logo">
      <% if signed_in? %>
      <%= link_to image_tag("logo.png"), "/home" %>
      <% else %>
      <%= link_to image_tag("logo.png"), "/" %>
      <% end %>
    </div>

    <% if signed_in? %>

    <div id="topbar">

      <div id="navmenu">
        <span><%= link_to "MUSIC", "/music" %></span>

        <div class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            SETLISTS <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Setlists", setlists_path %></li>
            <li><%= link_to "New Setlist", new_setlist_path %></li>
          </ul>
        </div>


        <span><%= link_to "My Circles", "#" %></span>

        <div class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            ACCOUNT <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          </ul>
        </div>
      </div>


      <div id="search_form">
        <%= form_tag 'songs/index', method: "get" do %>
        <span>Search</span> <%= text_field :search, params[:search] %>
        <% end %>
      </div>
    
    </div>

    <% else %>

    <div id="topbar">
      <div id="topbar_right"
        <%= link_to "SIGN IN HELP", "https://en.wikipedia.org/wiki/Login", :class => "btn-mini" %>
      </div>
    </div>

    <% end %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <title><%= full_title(yield(:title)) %></title>

      <%= stylesheet_link_tag 'humanity/jquery-ui-1.8rc3.custom', :media => 'screen' %>

      <%= stylesheet_link_tag 'music' %>
      <%= stylesheet_link_tag 'structure' %>
      <%= stylesheet_link_tag 'colors_fonts' %>

      <%= javascript_include_tag 'jquery-1.4.2.min' %>
      <%= javascript_include_tag 'jquery-ui-1.8rc3.custom.min' %>
      <%= javascript_include_tag 'jquery.livequery' %>
      <%= javascript_include_tag 'jquery.hoverIntent.minified' %>
      <%= javascript_include_tag 'application' %>

      <%= javascript_include_tag :defaults %>
      <%= csrf_meta_tag %>

  </head>

  <body>

      <%= render 'layouts/header' %>

    <div id="content">
      <div class="container">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert alert-#{key}") %>
        <% end %>

        <%= yield %>
      
      </div>
    </div>

      <%= render 'layouts/footer' %>

      <script type="text/javascript">
        <%= yield :javascript %>
      </script>

  </body>
</html>

app/views/pages/home.html.erb
<div id="sidebar">
	<h4>The Sidebar Headline</h4>
		<p>
			Lorem ipsum Esse nisi proident in in cupidatat proident est culpa laborum. Lorem ipsum Aliqua exercitation ad adipisicing deserunt eu sit in non. Lorem ipsum Proident laboris enim ea id consectetur in eiusmod. Lorem ipsum Veniam sunt velit in nisi incididunt eu id minim dolore aliqua commodo officia. Lorem ipsum Dolore pariatur mollit et ullamco et esse velit.
		</p>
</div>

<div id="content_main">
	<div class="content_greywrap">
		<div class="content_head">
		<h2>Welcome to AmateurMorpheus</h2>
		<p>This is the home page. You can't do anything here.</p>
		</div>

		<div class="content_body">
			<p>
				Lorem ipsum Esse nisi proident in in cupidatat proident est culpa laborum. Lorem ipsum Aliqua exercitation ad adipisicing deserunt eu sit in non. Lorem ipsum Proident laboris enim ea id consectetur in eiusmod. Lorem ipsum Veniam sunt velit in nisi incididunt eu id minim dolore aliqua commodo officia. Lorem ipsum Dolore pariatur mollit et ullamco et esse velit.
			</p><br>
			<p>
				Lorem ipsum Esse nisi proident in in cupidatat proident est culpa laborum. Lorem ipsum Aliqua exercitation ad adipisicing deserunt eu sit in non. Lorem ipsum Proident laboris enim ea id consectetur in eiusmod. Lorem ipsum Veniam sunt velit in nisi incididunt eu id minim dolore aliqua commodo officia. Lorem ipsum Dolore pariatur mollit et ullamco et esse velit.
			</p><br>
			<p>
				Lorem ipsum Esse nisi proident in in cupidatat proident est culpa laborum. Lorem ipsum Aliqua exercitation ad adipisicing deserunt eu sit in non. Lorem ipsum Proident laboris enim ea id consectetur in eiusmod. Lorem ipsum Veniam sunt velit in nisi incididunt eu id minim dolore aliqua commodo officia. Lorem ipsum Dolore pariatur mollit et ullamco et esse velit.
			</p><br>
			</p><br>

			<div id="circuschaser">
				<p>Visit <%= link_to "CircusCHASER.com", "http://circuschaser.com" %> if you're bored with this.</p>
			</div>
		</div>
	</div>
</div>

app/views/setlists/index.html.erb
<% provide(:title, "My Setlists") %>

<div id="sidebar">
  <h4>The Sidebar Headline</h4>
</div>

<div id="content_main">
  <div class="content_greywrap">
    <div class="content_head">
      <h2>My Setlists</h2>
    </div>
    
    <div class="content_body">
      <% if @setlists.size == 0 %>
        <div class="nothing_found">
          Sorry. Nothing found.
        </div>
      <% else %>

      <div id="songcount">
        Showing <%= pluralize(@setlists.all.count, "match") %>
      </div>

      <table class="piece">

        <% @setlists.each do |set| %>
        <tr>
          <td class="content_left">
            <%= set[:title] %>
            <p class="meta"><%= set[:performance_date] %></p>
          </td>
          <td class="content_right">
            <%= set[:description] %>
            <p class="meta">Contains <%= pluralize(set.songs.count, "song") %></p>
          </td>
          <td class="tag_block">
            <div id="linkbutton">
              <%= link_to "DELETE", set, method: :delete,
                    data: { confirm: "Do you really want to delete: #{set.title.upcase}?" } %>
            </div>
          </td>
        </tr>
        <% end %>
      </table>
    </div>

    <% end %>

  </div>
</div>

app/views/setlists/new.html.erb
<% provide(:title, "New Setlist") %>

<div id="sidebar">
  <h4>The Sidebar Headline</h4>
</div>

<div id="content_main">
  <div class="content_greywrap">
    <div class="content_head">
    	<h2>New Setlist</h2>
    </div>
    <div class="content_body">
    	<%= form_for(@setlist) do |f| %>
    	<%= render 'shared/error_messages', object: f.object %>

    	<%= f.label :title %>
    	<%= f.text_field :title %>

    	<%= f.label :description %>
    	<%= f.text_field :description %>

    	<%= f.label :performance_date %>
    	<%= f.text_field :performance_date %>

    	<%= f.submit "Create My Setlist", class: "btn btn-small" %>
    	<% end %>

    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%=h value %></div>
  <% end -%>
</div>

app/views/songs/index.html.erb
<% provide(:title, "My Music") %>

<div id="sidebar">
  <h4>The Sidebar Headline</h4>
</div>

<div id="content_main">
  <div class="content_greywrap">
    <div class="content_head">
      <h2>My Songs</h2>

          <div class="model_search">
            <%= form_tag songs_path, method: 'get' do %>
            <%= text_field_tag :search, params[:search] %>
          </div>
            <%= submit_tag "Search", class: "btn-small", name: nil %>
            <% end %>

      <%= will_paginate @songs %>
    </div>
    
    <div class="content_body">
      <% if @songs.size == 0 %>
        <div class="nothing_found">
          Sorry. Nothing found.
        </div>
      <% else %>

      <div id="songcount">
        Showing <%= pluralize(@songs.all.count, "match") %>
      </div>

      <table class="piece">

        <% @songs.each do |song| %>
        <tr>
          <td class="content_left">
            <%= song[:title] %>
            <p class="meta"><%= song[:composer_name] %></p>
          </td>
          <td class="content_right">
            <%= song[:album_name] %>
            <p class="meta"><%= song[:genre_name] %></p>
          </td>
          <td class="tag_block">
            <div></div>
          </td>
        </tr>
        <% end %>
      </table>
    </div>

    <% end -%>

  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<div class="container">
	<div class="formbox span6 offset3">
		<h3>Update your profile</h3>
		<br></br>
		<%= gravatar_for @user %>
		<a href="http://gravatar.com/emails">change</a>
		<br></br>
		<br></br>

		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			
			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirm Password" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Save changes", class: "btn btn-small" %>
		<% end %>
	</div>
</div>

app/views/users/new.html.erb
<%= provide(:title, "Sign up") %>

<div class="container">
  <div class="formbox">
    <h3>Create an Account</h3>
    <br></br>

    <%= form_for(@user) do |f| %>
    	<%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-small" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>

<div class="container">
	<div class="formbox span6 offset3">
		<h3>
			<%= gravatar_for @user %>
			<%= @user.name %>
		</h3><br>
		<p>This is your Account page.</p></br>
		<div>
			<p>
				Lorem ipsum Esse nisi proident in in cupidatat proident est culpa laborum. Lorem ipsum Aliqua exercitation ad adipisicing deserunt eu sit in non. Lorem ipsum Proident laboris enim ea id consectetur in eiusmod.
			</p><br>
			<p id="linkbutton">
				Go to the <%= link_to "MAIN", "/home" %> page.
			</p>
		</div>
	</div>
</div>